

<?php

//$this->getRequest()->setParam('p',1);
$_productCollection=$this->getSpecialProductList();
$_helper = $this->helper('catalog/output');

$countpage = $this->getSpecialProductCountpage();

?>
<?php echo $this->getChildHtml("navtop") ?>
<div class="amshopby-page-container">

<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
 
    <div class="toolbar">
		<div class="pager">
		<?php if($countpage > 1): ?>
			<input type="hidden" value="<?php echo $countpage ?>" id="last_page" />
			<a class="next  lnk-next-1" href="<?php echo $this->getUrl('custom/index/specialproduct')."?p=2"; ?>">
					</a>
		<?php endif; ?>
		</div>
	</div>
     
            <?php // Grid Mode ?>
            <!-- Like Facebook --> 
               <div id="fb-root"></div>
                <script src="http://connect.facebook.net/en_US/all.js"></script>
                
                <script type="text/javascript">
                    jQuery(document).ready(function(){
                        jQuery('.products-grid li.item').hover(function(){
                            var x =jQuery(this).find('.overHidden');
                            if(x.css("display") == "none"){
                                 jQuery(this).find('.overHidden').show(); // toggle the display of the button
                                 FB.XFBML.parse(this); //re-parse xfbml
                             }
                        });
                    });
                </script>
            <!-- End Like Facebook -->
            <?php $_collectionSize = $_productCollection->count() ?>
            <?php $_columnCount = 3; ?>
            <?php $i=0;
            foreach ($_productCollection as $_product): ?>
            <?php if ($i++%$_columnCount==0): ?>
    <ul class="products-grid">
            <?php endif ?>
        <li class="item first">
            <?php $now = date("Y-m-d");
                $newsFrom= substr($_product->getData("news_from_date"),0,10);
                $newsTo=  substr($_product->getData("news_to_date"),0,10);
                if ($now>=$newsFrom && $now<=$newsTo){ echo "<div class='discount-list'><p>New</p></div>";};
            ?>
            <?php if($_product->getSpecialPrice() != 0){ ?>
                 <?php $discount = 100 - round(($_product->getSpecialPrice()/$_product->getPrice())*100); ?>
                 <?php echo "<div class='discount-list'><p>- ".$discount."% </p></div>" ; 
            }?>
			<?php $image = $this->helper('catalog/image')->init($_product, 'small_image');?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/cropimage')->cropImage(PPRODUCT_LIST_WIDTH,PPRODUCT_LIST_HEIGHT,$image ); ?>"  alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            <div class="socialHideToolBar">
                <?php 
				 $vendor_data = FavoredMinds_Vendor_Block_Vendor_Renderer_Vendor::getVendorInfo($_product->getData('manufacturer'),array("company_name","path"));
				 //$vendor = Mage::getModel("vendor/vendor")->load($vendor_data['vendor_id']);?>
                <div class="social">
                    <img class="ui-icon icon-19" src="<?php echo $this->getSkinUrl('images/dummy.gif')?>" alt="" />
                    <a href="<?php echo Mage::getBaseUrl().$vendor_data['path']; ?>">
				<?php echo $vendor_data['company_name'] ?></a></div>
                <div class="quatang" ><img src="<?php echo $this->getSkinUrl('images/quatang.png');?>" alt="quatang"/></div>
                <div class="overHidden" style="display: none;">
                    <fb:like class="face-likes" href="<?php echo $_product->getProductUrl() ?>" style="position: relative!important; margin-right: -5px; float: right;" send="false" layout="button_count" width="100" show_faces="false" font="arial"></fb:like>
                </div>
            </div>
            <div class="content-product" style="overflow: hidden; position: relative;">
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                            <?php if($_product->getRatingSummary()): ?>
                                <?php //echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                            <?php endif; ?>
            
                
                <?php echo $this->getPriceHtml($_product, true) ?>
                <div class="add_button_cart">
                <?php if($_product->isSaleable()): ?>
    					<!--<a class="btn-buy" title="<?php echo $this->__('Add to Cart') ?>" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__("Mua Hàng") ?></a>-->
    					<?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
    						<a class="btn-buy" title="<?php echo $this->__('Add to Cart') ?>" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__("Mua Hàng") ?></a>
                            <span id='ajax_loader<?php echo $_product->getId()?>' style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span>
                            <?php } else { ?>
    							<a class="btn-buy" title="<?php echo $this->__('Add to Cart') ?>" onclick="showOptions('<?php echo $_product->getId()?>')"><?php echo $this->__("Mua Hàng") ?></a>
                            	<a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'></a>
                        <?php }  ?>
    						
                <?php else: ?>
                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                <?php endif; ?>
                </div>
            </div>
        </li>
            <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
    </ul>
                <?php endif ?>
        <?php endforeach ?>
   
	</div>



<div style="display:none" class="amshopby-overlay"><img src="<?php echo $this->getSkinUrl('images/amshopby-overlay.gif')?>" /></div>
</div>

<a id="msg" href="#inline" style="display:none"></a>
<div style="display:none" >
<div id="inline" >
	<p class="msg-text"></p>
	<a href="javascript:;" onclick="jQuery.fancybox.close();">Close</a>
</div>
</div>
<?php endif; ?>

