<div class="discount">
    <div class="discount-form">
        <input type="hidden" name="remove" id="remove-coupone" value="0" />
        <label><?php echo $this->__('Discount Codes') ?></label>
        <div class="input-box">
            <input title="<?php echo $this->__('Enter your coupon code if you have one.') ?>" class="input-text" id="coupon_code" name="coupon_code" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" />
        </div>
        <button type="button" title="<?php echo $this->__('Apply Coupon') ?>" class="button" onclick="setDiscount(false)" value="<?php echo $this->__('Apply Coupon') ?>"><span><span><?php echo $this->__('Apply Coupon') ?></span></span></button>
        <?php if(strlen($this->getCouponCode())): ?>
            &nbsp; <button type="button" title="<?php echo $this->__('Cancel Coupon') ?>" class="button" onclick="setDiscount(true)" value="<?php echo $this->__('Cancel Coupon') ?>"><span><span><?php echo $this->__('Cancel Coupon') ?></span></span></button>
        <?php endif;?>
    </div>
</div>
<div class="clear"></div>
