<div class="checkout-agreements discount" id="discount-coupon-form">
    <?php echo $this->getChildHtml('coupon') ?>
</div>

<div class="order-review" id="checkout-review-load">
    <?php echo $this->getChildHtml('info') ?>
    <?php echo $this->getChildHtml('order.review', true, true);?>
</div>

<?php echo $this->getChildHtml('additional') ?>

<div id="checkout-review-submit">
    <?php echo $this->getChildHtml('agreements') ?>
    <div class="buttons-set" id="review-buttons-container">
        <p class="f-left"><?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Your Cart') ?></a></p>
        <?php echo $this->getChildHtml('button') ?>
        <span class="please-wait" id="review-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
        </span>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        review = new Review('checkoutSteps', '<?php echo $this->getUrl('checkout/onepage/saveOrder') ?>', '<?php echo $this->getUrl('checkout/onepage/success') ?>');
    //]]>
    </script>
</div>
<!--
<div class="control">
    <a class="lnk-back float-l" title="VỀ TRANG TRƯỚC" href="javascript:window.history.back();">VỀ TRANG TRƯỚC</a>
    <a class="lnk-continue right" title="TIẾP TỤC" href="product-step3.html">TIẾP TỤC</a>
</div>
-->

