<?php

define("FEATURED_PRODUCT_WIDTH",224);
define("FEATURED_PRODUCT_HEIGHT",226);
define("PPRODUCT_LIST_WIDTH",296);
define("PPRODUCT_LIST_HEIGHT",298);

define("PRODUCT_DETAIL_WIDTH",364);
define("PRODUCT_DETAIL_HEIGHT",360);

define("DEFAULT_NUMBER_VENDOR_ON_FAVOURITE",8);
define("MAXIMUM_HP_DES",60);
define("MAXIMUM_HP_DES_SLIDE",50);
define("DEFAULT_NUMBER_VENDOR_ON_PAGE",6);

define("HOT_PRODUCT_SLIDER_COLUMN",4);
define("HOT_PRODUCT_SLIDER_ITEM_NUMBER",20);

define("ROLE_VENDOR_ID",6);
define("GROUP_PRODUCT_INFO",262);
define("GROUP_PRODUCT_IMAGE",99);




