<div class="box best-selling">
    <h3>Hàng Nóng <span>Mua Nhanh</span></h3>
                <div id="home-top-slider" class="hot-product">
            <ul class="jcarousel-pager-center">
                                    <li><dl>                            <dd class = "hot-item">
                                <a href="http://www.muafast.com/index.php/catalog/product/view/id/3861/">

                                                                        <img class="product-img"
                                         src="http://www.muafast.com/media/catalog/product/cache/0/small_image/224x/17f82f742ffe127f42dca9de82fb58b1/c/k/ck01.jpg"
                                         alt="" />
                                </a>
                                <p class="product-description">
                                    <a href="http://www.muafast.com/index.php/catalog/product/view/id/3861/">Áo khoác jean AKJ-04</a>
                                    <span class="hot-product-hover">
                                                                            <span>Giá: <strong><span class="price">560.000 ₫</span></strong></span>
                                                                        <span class="color" style=" float: right;">
                                        </span>
                                    </span>
                                </p>
                            </dd>
                                                                                                                                    <dd class = "hot-item">
                                <a href="http://www.muafast.com/index.php/catalog/product/view/id/3860/">

                                                                        <img class="product-img"
                                         src="http://www.muafast.com/media/catalog/product/cache/0/small_image/224x/17f82f742ffe127f42dca9de82fb58b1/v/t/vt_006_019_2_20.jpg"
                                         alt="" />
                                </a>
                                <p class="product-description">
                                    <a href="http://www.muafast.com/index.php/catalog/product/view/id/3860/">Áo khoác jean AKJ-06</a>
                                    <span class="hot-product-hover">
                                                                            <span>Giá: <strong><span class="price">520.000 ₫</span></strong></span>
                                                                        <span class="color" style=" float: right;">
                                        </span>
                                    </span>
                                </p>
                            </dd>
                                                                                                                                    <dd class = "hot-item">
                                <a href="http://www.muafast.com/index.php/catalog/product/view/id/3859/">

                                                                        <img class="product-img"
                                         src="http://www.muafast.com/media/catalog/product/cache/0/small_image/224x/17f82f742ffe127f42dca9de82fb58b1/v/t/vt_006_018_1_19.jpg"
                                         alt="" />
                                </a>
                                <p class="product-description">
                                    <a href="http://www.muafast.com/index.php/catalog/product/view/id/3859/">Áo khoác jean AKJ-07</a>
                                    <span class="hot-product-hover">
                                                                            <span>Giá: <strong><span class="price">450.000 ₫</span></strong></span>
                                                                        <span class="color" style=" float: right;">
                                        </span>
                                    </span>
                                </p>
                            </dd>
                                                                                                                                    <dd class = "hot-item last">
                                <a href="http://www.muafast.com/index.php/catalog/product/view/id/3911/">

                                                                        <img class="product-img"
                                         src="http://www.muafast.com/media/catalog/product/cache/0/small_image/x226/17f82f742ffe127f42dca9de82fb58b1/k/e/ken_042_02_14.jpg"
                                         alt="" />
                                </a>
                                <p class="product-description">
                                    <a href="http://www.muafast.com/index.php/catalog/product/view/id/3911/">Áo khoác da AKD-01</a>
                                    <span class="hot-product-hover">
                                                                            <span>Giá: <strong><span class="price">320.000 ₫</span></strong></span>
                                                                        <span class="color" style=" float: right;">
                                        </span>
                                    </span>
                                </p>
                            </dd>
                            </dl></li>                                                                            <li><dl>                            <dd class = "hot-item">
                                <a href="http://www.muafast.com/index.php/catalog/product/view/id/3842/">

                                                                        <img class="product-img"
                                         src="http://www.muafast.com/media/catalog/product/cache/0/small_image/x226/17f82f742ffe127f42dca9de82fb58b1/v/t/vt_006_006_2_21.jpg"
                                         alt="" />
                                </a>
                                <p class="product-description">
                                    <a href="http://www.muafast.com/index.php/catalog/product/view/id/3842/">Áo khoác da AKD-29</a>
                                    <span class="hot-product-hover">
                                                                            <span>Giá: <strong><span class="price">420.000 ₫</span></strong></span>
                                                                        <span class="color" style=" float: right;">
                                        </span>
                                    </span>
                                </p>
                            </dd>
                                                                                                                                    <dd class = "hot-item">
                                <a href="http://www.muafast.com/index.php/catalog/product/view/id/3840/">

                                                                        <img class="product-img"
                                         src="http://www.muafast.com/media/catalog/product/cache/0/small_image/224x/17f82f742ffe127f42dca9de82fb58b1/v/t/vt_006_002_2_20.jpg"
                                         alt="" />
                                </a>
                                <p class="product-description">
                                    <a href="http://www.muafast.com/index.php/catalog/product/view/id/3840/">Áo khoác da AKD-36</a>
                                    <span class="hot-product-hover">
                                                                            <span>Giá: <strong><span class="price">450.000 ₫</span></strong></span>
                                                                        <span class="color" style=" float: right;">
                                        </span>
                                    </span>
                                </p>
                            </dd>
                                                                                                                                    <dd class = "hot-item">
                                <a href="http://www.muafast.com/index.php/catalog/product/view/id/3750/">

                                                                        <img class="product-img"
                                         src="http://www.muafast.com/media/catalog/product/cache/0/small_image/x226/17f82f742ffe127f42dca9de82fb58b1/h/a/haha0002a_4.jpg"
                                         alt="" />
                                </a>
                                <p class="product-description">
                                    <a href="http://www.muafast.com/index.php/catalog/product/view/id/3750/">Áo len A943</a>
                                    <span class="hot-product-hover">
                                                                            <span>Giá: <strong><span class="price">165.000 ₫</span></strong></span>
                                                                        <span class="color" style=" float: right;">
                                        </span>
                                    </span>
                                </p>
                            </dd>
                                                                                                                                    <dd class = "hot-item last">
                                <a href="http://www.muafast.com/index.php/catalog/product/view/id/3918/">

                                                                        <img class="product-img"
                                         src="http://www.muafast.com/media/catalog/product/cache/0/small_image/224x/17f82f742ffe127f42dca9de82fb58b1/y/a/yame0009a_-_copy.jpg"
                                         alt="" />
                                </a>
                                <p class="product-description">
                                    <a href="http://www.muafast.com/index.php/catalog/product/view/id/3918/">Quần Jean A1 7488</a>
                                    <span class="hot-product-hover">
                                                                            <span>Giá: <strong><span class="price">285.000 ₫</span></strong></span>
                                                                        <span class="color" style=" float: right;">
                                        </span>
                                    </span>
                                </p>
                            </dd>
                            </dl></li>                                                                            <li><dl>                            <dd class = "hot-item">
                                <a href="http://www.muafast.com/index.php/catalog/product/view/id/3916/">

                                                                        <img class="product-img"
                                         src="http://www.muafast.com/media/catalog/product/cache/0/small_image/224x/17f82f742ffe127f42dca9de82fb58b1/y/a/yame0008a_-_copy.jpg"
                                         alt="" />
                                </a>
                                <p class="product-description">
                                    <a href="http://www.muafast.com/index.php/catalog/product/view/id/3916/">Quần Jean A1 7494</a>
                                    <span class="hot-product-hover">
                                                                            <span>Giá: <strong><span class="price">285.000 ₫</span></strong></span>
                                                                        <span class="color" style=" float: right;">
                                        </span>
                                    </span>
                                </p>
                            </dd>
                                                                                                                                    <dd class = "hot-item">
                                <a href="http://www.muafast.com/index.php/catalog/product/view/id/3914/">

                                                                        <img class="product-img"
                                         src="http://www.muafast.com/media/catalog/product/cache/0/small_image/224x/17f82f742ffe127f42dca9de82fb58b1/y/a/yame0007a_-_copy.jpg"
                                         alt="" />
                                </a>
                                <p class="product-description">
                                    <a href="http://www.muafast.com/index.php/catalog/product/view/id/3914/">Quần Jean HMS 7415</a>
                                    <span class="hot-product-hover">
                                                                            <span>Giá: <strong><span class="price">385.000 ₫</span></strong></span>
                                                                        <span class="color" style=" float: right;">
                                        </span>
                                    </span>
                                </p>
                            </dd>
                                                                                                                                    <dd class = "hot-item">
                                <a href="http://www.muafast.com/index.php/catalog/product/view/id/3294/">

                                                                        <img class="product-img"
                                         src="http://www.muafast.com/media/catalog/product/cache/0/small_image/x226/17f82f742ffe127f42dca9de82fb58b1/1/8/188300191857_3.jpg"
                                         alt="" />
                                </a>
                                <p class="product-description">
                                    <a href="http://www.muafast.com/index.php/catalog/product/view/id/3294/">CK EUPHORIA BLOSSOM EDT 100ml</a>
                                    <span class="hot-product-hover">
                                                                            <span>Giá: <strong><span class="price">1.827.500 ₫</span></strong></span>
                                                                        <span class="color" style=" float: right;">
                                        </span>
                                    </span>
                                </p>
                            </dd>
                                                                                                                                    <dd class = "hot-item last">
                                <a href="http://www.muafast.com/index.php/catalog/product/view/id/3295/">

                                                                        <img class="product-img"
                                         src="http://www.muafast.com/media/catalog/product/cache/0/small_image/224x/17f82f742ffe127f42dca9de82fb58b1/3/4/3414202011752_3.jpg"
                                         alt="" />
                                </a>
                                <p class="product-description">
                                    <a href="http://www.muafast.com/index.php/catalog/product/view/id/3295/">DF COOL WATER EDT 100ml</a>
                                    <span class="hot-product-hover">
                                                                            <span>Giá: <strong><span class="price">1.623.500 ₫</span></strong></span>
                                                                        <span class="color" style=" float: right;">
                                        </span>
                                    </span>
                                </p>
                            </dd>
                            </dl></li>                                                                            <li><dl>                            <dd class = "hot-item">
                                <a href="http://www.muafast.com/index.php/catalog/product/view/id/3289/">

                                                                        <img class="product-img"
                                         src="http://www.muafast.com/media/catalog/product/cache/0/small_image/224x/17f82f742ffe127f42dca9de82fb58b1/1/8/188300162505_3.jpg"
                                         alt="" />
                                </a>
                                <p class="product-description">
                                    <a href="http://www.muafast.com/index.php/catalog/product/view/id/3289/">CK EUPHORIA WOMEN EDP 100ml</a>
                                    <span class="hot-product-hover">
                                                                            <span>Giá: <strong><span class="price">1.972.000 ₫</span></strong></span>
                                                                        <span class="color" style=" float: right;">
                                        </span>
                                    </span>
                                </p>
                            </dd>
                                                                                                                                    <dd class = "hot-item">
                                <a href="http://www.muafast.com/index.php/catalog/product/view/id/3283/">

                                                                        <img class="product-img"
                                         src="http://www.muafast.com/media/catalog/product/cache/0/small_image/224x/17f82f742ffe127f42dca9de82fb58b1/1/8/188300104406_3.jpg"
                                         alt="" />
                                </a>
                                <p class="product-description">
                                    <a href="http://www.muafast.com/index.php/catalog/product/view/id/3283/">CK BE EDT 100ml</a>
                                    <span class="hot-product-hover">
                                                                            <span>Giá: <strong><span class="price">1.972.000 ₫</span></strong></span>
                                                                        <span class="color" style=" float: right;">
                                        </span>
                                    </span>
                                </p>
                            </dd>
                                                                                                                                    <dd class = "hot-item">
                                <a href="http://www.muafast.com/index.php/catalog/product/view/id/3330/">

                                                                        <img class="product-img"
                                         src="http://www.muafast.com/media/catalog/product/cache/0/small_image/x226/17f82f742ffe127f42dca9de82fb58b1/6/8/688575201895_3.jpg"
                                         alt="" />
                                </a>
                                <p class="product-description">
                                    <a href="http://www.muafast.com/index.php/catalog/product/view/id/3330/">CHLOE EDP 75ml</a>
                                    <span class="hot-product-hover">
                                                                            <span>Giá: <strong><span class="price">2.397.000 ₫</span></strong></span>
                                                                        <span class="color" style=" float: right;">
                                        </span>
                                    </span>
                                </p>
                            </dd>
                                                                                                                                    <dd class = "hot-item last">
                                <a href="http://www.muafast.com/index.php/catalog/product/view/id/3913/">

                                                                        <img class="product-img"
                                         src="http://www.muafast.com/media/catalog/product/cache/0/small_image/224x/17f82f742ffe127f42dca9de82fb58b1/y/a/yame0006a_-_copy.jpg"
                                         alt="" />
                                </a>
                                <p class="product-description">
                                    <a href="http://www.muafast.com/index.php/catalog/product/view/id/3913/">Quần Jean Mado 7406</a>
                                    <span class="hot-product-hover">
                                                                            <span>Giá: <strong><span class="price">385.000 ₫</span></strong></span>
                                                                        <span class="color" style=" float: right;">
                                        </span>
                                    </span>
                                </p>
                            </dd>
                            </dl></li>                                                                    </ul>
        </div>
    </div>
   