<div class="box best-selling">

    <?php $vendorList = $this->getVendorsOnHomePage(); ?>
    
    
    <!--    
    <ul class="lst-slide">
        <li><a href="#" title=""><img src="<?php //echo $this->getSkinUrl("images/dummy.gif")           ?>" class="ui-icon icon-05" alt="" /></a></li>
        <li><a href="#" title=""><img src="<?php //echo $this->getSkinUrl("images/dummy.gif")           ?>" class="ui-icon icon-05" alt="" /></a></li>
        <li><a href="#" title=""><img src="<?php //echo $this->getSkinUrl("images/dummy.gif")           ?>" class="ui-icon icon-05 active" alt="" /></a></li>
        <li><a href="#" title=""><img src="<?php //echo $this->getSkinUrl("images/dummy.gif")           ?>" class="ui-icon icon-05" alt="" /></a></li>
        <li><a href="#" title=""><img src="<?php //echo $this->getSkinUrl("images/dummy.gif")           ?>" class="ui-icon icon-05" alt="" /></a></li>
    </ul>
    -->
</div>

<script type="text/javascript">
    
    function home_slider_carousel_initCallback(carousel)
    {
        // Disable autoscrolling if the user clicks the prev or next button.
        carousel.buttonNext.bind('click', function() {
            carousel.startAuto(0);
        });

        carousel.buttonPrev.bind('click', function() {
            carousel.startAuto(0);
        });

        // Pause autoscrolling if the user moves with the cursor over the clip.
        carousel.clip.hover(function() {
            carousel.stopAuto();
        }, function() {
            carousel.startAuto();
        });
    };
    
    // Ride the carousel...
    jQuery(document).ready(function() {
        jQuery(".favourites-slider").jcarousel({
            scroll: 1,
            visible: 1,
            auto: 7,
            wrap: 'last',
            buttonPrevHTML: '<a class="btn-previous" title="<?php echo $this->__("Previous") ?>" href="javascript:void(0)"><p class="prev_slider"></p></a>',
            buttonNextHTML: '<a  title="<?php echo $this->__("Continue") ?>" class="btn-continue" href="javascript:void(0)"><p class="next_slider"></p></a>',
            initCallback: home_slider_carousel_initCallback
        });
    });
    
</script>