<script type="text/javascript">
	//document.maximumUploads = <?php $ini_setting = ini_get('max_file_uploads'); echo($ini_setting); ?>;
	document.potentialUploads = 0;
	function addUpload(ID) {
		++document.potentialUploads;
		if (document.potentialUploads > document.maximumUploads) {
			alert("<?php echo Mage::helper('autoswatchesplus')->__('Sorry, this server allows a maximum of '.$ini_setting.' uploads at a time. Please upload the current swatches to upload more.'); ?>");
		} else {
			var newField = "<input type=\"file\" name=\"autoswatchesplus_swatch["+ID+"]\">";
			document.getElementById("autoswatchesplus_upload_swatch_area_"+ID).innerHTML = newField;
		}
	}
</script>
<form method="post" enctype="multipart/form-data" action="<?php echo $this->getSubmitUrl(); ?>">
<?php
echo $this->getBlockHtml('formkey');
$swatchsize = Mage::helper('autoswatchesplus/data')->getSwatchSize('null');
?> 
<div>
<ul class="messages">
    <li class="notice-msg">
        <ul>
            <li><?php echo Mage::helper('catalog')->__('For best results, please upload square .jpg images, preferably 50 x 50.<br>
            To use auto swatches, please go to Manage Label / Options and enter the HEX code of your color in the Admin value field. Example: Green #83F52C<br>
            The preview image below is exactly how your swatch will look based on your default swatch size setting in the configuration.') ?></li>
        </ul>
    </li>
</ul>
</div>
<div class="entity-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('autoswatchesplus')->__('Manage Swatches') ?></h4>
        
        <div class="form-buttons">
            <button style="" type="submit" class="scalable save" type="button"><span>Update Swatches</span></button>
        </div>
    </div>
    <div class="box">
            <div class="hor-scroll">
            <table cellspacing="5">
                <tr>
                    <th width="150"><?php echo Mage::helper('autoswatchesplus')->__('Swatch Label') ?></th>
                    <th width="10"></th>
                    <th width="250"><?php echo Mage::helper('autoswatchesplus')->__('Upload Swatch Image') ?></th>
                    <th width="10"></th>
                    <th><?php echo Mage::helper('autoswatchesplus')->__('Preview') ?></th>
                    <th width="10"></th>
                    <th><?php echo Mage::helper('autoswatchesplus')->__('Swatch Type') ?></th>
                    <th width="10"></th>
                    <th><?php echo Mage::helper('autoswatchesplus')->__('HEX Code') ?></th>
                    <th width="10"></th>
                    <th><?php echo Mage::helper('autoswatchesplus')->__('Delete') ?></th>
                </tr>
                <?php foreach ($this->getOptionsCollection() as $option): ?>
                <?php $name = $option->getData('value');?>
                <?php
                $theName = explode('#',$name);
               	if (isset($theName[1])) {
               		$color_value = '#'.$theName[1];
					$color_name = $theName[0];
				} else {
					$color_name = $theName[0];
				}
				?>
                <tr>
                    <td><?php echo $color_name; ?></td>
                    <td></td>
                    <td>
                    	<div id="autoswatchesplus_upload_swatch_area_<?php echo $option->getData('option_id'); ?>">
						<?php if ($this->getIcon($option) || isset($theName[1])) { ?>
                        	<?php $addOrEdit = 'Edit '; ?>
                      	<?php } else { ?>
                        	<?php $addOrEdit = 'Add '; } ?>
                        	<a href="#" onclick="addUpload(<?php echo $option->getData('option_id'); ?>); return false;">
								<?php echo $addOrEdit . Mage::helper('autoswatchesplus')->__('Swatch Image'); ?>
							</a>
						</div>
                    </td>
                    <td></td>
                    <td align="center">
                        <?php
                        $iconUrl = $this->getIcon($option);
                        if ($iconUrl):
                        ?>
                            <img src="<?php echo $iconUrl; ?>" alt="" width="<?php echo $swatchsize ?>px" height="<?php echo $swatchsize ?>px">
                            <?php $auto = 'Image'; ?>
                        <?php else: 
                       		if(isset($theName[1])) 
							{
								echo '<div style="height:'.$swatchsize.'px; width:'.$swatchsize.'px; background-color:'.$color_value.';"></div>';
								$auto = 'Auto';
							} else {
								echo Mage::helper('autoswatchesplus')->__('No');
								echo '<br>';
								echo Mage::helper('autoswatchesplus')->__('Swatch');
								$auto = '-';
							}
							
							?>
                        <?php endif; ?>
                    </td>
                    <td></td>
                    <td align="center"><?php echo $auto; ?></td>
                    <td></td>
                    <td align="center">
						<?php if (isset($theName[1])) { ?>
                        <?php echo strtoupper($color_value); ?>
                        <?php } else { ?>
                        <?php echo '-'; } ?>
                   	</td>
                    <td></td>
                    <td align="center"><input type="checkbox" value="1" name="autoswatchesplus_swatch_delete[<?php echo $option->getData('option_id'); ?>]"></td>
                </tr>
                <?php endforeach; ?>
                
            </table>
            </div>
    </div>
</div>

</form>