<?php $_filters = $this->getActiveFilters() ?>

<?php $_removeTxt = Mage::helper('catalog')->__('Remove This Item') ?>
<?php if (!empty($_filters)): ?>

    <?php foreach ($_filters as $_filter): ?>
        <?php if ($_filter->getFilter()->getRequestVar() == 'price'): ?>
            <?php if (!$_filter->getIsMultiValues()): ?>
                <dl class="cur_price">
                    <ul id="cate_list" class="lst-category-1">
                        <li class="amshopby-cat amshopby-cat-level-1">
                            <a href="<?php echo $_filter->getRemoveUrl() ?>" class="amshopby-attr " title="<?php echo $_removeTxt ?>">
                                <span><span><?php echo strip_tags($_filter->getLabel()) ?></span></span>
                            </a>
                        </li>
                    </ul>
                </dl>
            <?php endif; ?>
        <?php endif; ?>
      
    <?php endforeach; ?>

    <?php /*
      <?php if (Mage::helper('amshopby')->isVersionLessThan(1, 4)): ?>
      <h4><?php echo $this->__('Currently Shopping by') ?></h4>
      <ol class="narrowed-category">
      <?php else: ?>
      <p class="block-subtitle"><?php echo Mage::helper('catalog')->__('Currently Shopping by') ?></p>
      <ol class="currently">
      <?php endif; ?>
      <?php foreach ($_filters as $_filter): ?>
      <li>
      <?php if (!$_filter->getIsMultiValues()): ?>
      <?php if (Mage::helper('amshopby')->isVersionLessThan(1, 4)): ?>
      <a href="<?php echo $_filter->getRemoveUrl() ?>" class="widget-btn" title="<?php echo $_removeTxt ?>"><img src="<?php echo $this->getSkinUrl('images/list_remove_btn.gif') ?>" alt="<?php echo $_removeTxt ?>" /></a>
      <?php else: ?>
      <a href="<?php echo $_filter->getRemoveUrl() ?>" class="btn-remove" title="<?php echo $_removeTxt ?>"><?php echo $_removeTxt ?></a>
      <?php endif; ?>
      <?php endif; ?>
      <span class="label"><?php echo Mage::helper('catalog')->__($_filter->getName()) ?>:</span> <?php echo $_filter->getLabel() ?>
      </li>
      <?php endforeach; ?>
      </ol>
      <?php if (Mage::helper('amshopby')->isVersionLessThan(1, 7)): ?>
      <div class="actions"><a href="<?php echo Mage::helper('amshopby/url')->getFullUrl(array(), 1) ?>"><?php echo Mage::helper('catalog')->__('Clear All') ?></a></div>
      <?php endif; */ ?>

<?php endif; ?>