<div id="transaction_history_box">
<?php echo $this->getToolbarHtml()?>
<?php $transactions = $this->getTransaction();?>
<table id="my-transaction-table" class="data-table">
    <col width="1">
    <col width="1">
    <!-- <col width="1"> -->
    <col width="1">
    <col width="1">
    <col width="1">
        <thead>
            <tr>
                <th><?php echo $this->__("Date")?></th>
                <th style="text-align: center;"><?php echo $this->__("Points")?></th>
                <th style="text-align: center;"><?php echo $this->__("Balance")?></th>
                <th><?php echo $this->__("Transaction Details")?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($transactions as $transaction):?>
            <tr>
                    <td style="width: 80px;"><?php echo $this->formatDate($transaction->getTransactionTime())." ".$this->formatTime($transaction->getTransactionTime())?></td>
                    <td style="text-align: center;"><span class="price"><?php echo $this->formatAmount($transaction->getAmount(), $transaction->getTypeOfTransaction())?></span></td>
                    <td style="text-align: center;"><span class="price"><?php echo $transaction->getData('balance')?></span></td>
					<?php  if($transaction->getTransactionDetail()==-1): ?>
					<td style="width: 230px;"><?php echo $this->__('Tôi đẹp trong mắt ai'); ?></td>
					<?php else: ?>
                    <td style="width: 230px;"><?php echo $this->getTransactionDetail($transaction->getTypeOfTransaction(),$transaction->getTransactionDetail(), $transaction->getStatus())?></td>
					<?php endif; ?>
           	</tr>
        <?php endforeach;?>
      	</tbody>
</table>

<?php echo $this->getToolbarHtml()?>

</div>
<script type="text/javascript">decorateTable('my-transaction-table')</script>